### ISSUE TITLE
Download EXR only or by date

### ISSUE THREAD

**Issue by LMBits** [agmmnn/polydown#2]
Any chance it could download EXR files only? Also, could it work by date? Just so in case you got half of the library but you want to download the other half from a certain date.

**Comment by agmmnn** [comment]
added `-ff`, `--fileformat` argument for hdris (hdr, exr) https://github.com/agmmnn/polydown/releases/tag/v0.3.2

>  _...Just so in case you got half of the library but you want to download the other half from a certain date._

In this case, you can run polydown in the same folder as the hdri's, if the filenames are the same and you don't enter the --overwrite argument it will continue without downloading the existing files.
