### ISSUE TITLE
Throws an error when I try to use it

### ISSUE THREAD

**Issue by ghost** [agmmnn/polydown#3]
![image](https://github.com/agmmnn/polydown/assets/89741444/a05da996-4db5-40b1-96fd-b15804b62cfa)

**Comment by agmmnn** [comment]
I added the `--tone` argument in the last version but I only passed it for "hdris" and forgot the "models", "textures" functions. I added it now. Thanks.

Try the new release.
https://github.com/agmmnn/polydown/releases/tag/v0.3.1
